name: CI

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ hashFiles('Cargo.lock') }}

      - name: Build
        run: cargo build
